version: '3'

services:
  cli-app:
    image: craftcms/nginx:7.3
    container_name: craft-lilt-plugin-nginx
    working_dir: /craft-lilt-plugin
    volumes:
      - ./:/craft-lilt-plugin

  mysql-test:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: "craft-lilt-test"
      MYSQL_USER: "craft-lilt-test"
      MYSQL_PASSWORD: "craft-lilt-test"
    container_name: craft-lilt-plugin-mysql-test

  wiremock:
    image: wiremock/wiremock
    container_name: craft-lilt-plugin-wiremock
    command: --port 80 --verbose