name: 🧪 Tests on multiple CraftCMS versions

on:
  push:
    branches:
      - 5.x # CraftCMS v5
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        craft_version: [
          "5.0.0",
        ]
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v2

      - name: 🧾 Set environment variables
        id: step_one
        run: |
          echo "PHP_VERSION=8.1" >> $GITHUB_ENV
          echo "CRAFT_VERSION=${{ matrix.craft_version }}" >> $GITHUB_ENV

      - name: 🧪 Run tests for CraftCMS ${{ matrix.craft_version }}
        run: make test-craft-versions
